Taula d'estadístics descriptius
irene187/shiny_app pull request #6
Opened 2024-11-14 11:45 UTC by sandraam22

He afegit una funció que crea un data.frame amb estadístics descriptius

2024-11-19 10:29 UTC, irene187 requested changes
bones sandra, que guai la proposta, m'agrada molt a més l'estructura del codi d'agrupar per separat noms i resultats! Estem aquí amb el manel i el miquel fent proves de què passa amb la opció de revisió de codi i request changes. aleshores, si ens tires un cable, et demanem un canvi, a veure què passa. Per exemple, reordenar els resultats de la taula aixi: mitjana, variancia, dt, mínim, Q1, Q2, Q3, màxim, N, NA. I potser si t'animes, afegir el coeficient de variació (100 * dt/mitjana). 
merci!

2024-11-19 11:02 UTC, sandraam22 commented
Hola Irene,
Gràcies!
D'acord, he fet els canvis que proposeu però he afegit també el valor "mínim" perquè potser us l'heu deixat en l'enumeració d'estadístics que m´heu proposat.
Per qualsevol cosa, en parlem!

2024-11-19 11:03 UTC, sandraam22 commented
Crec que he tancat el comentari i alhora el pull request... encara estic aprenent!

2024-11-21 11:02 UTC, irene187 commented
crec que ja ho he integrat. anem a mirar-ho :)

2024-11-21 11:02 UTC, closed without merging